# TP2 word embedding

In [1]:
## one hot vect

In [3]:
pip install tensorflow

     |████████████████████████████████| 458.4 MB 3.1 kB/s eta 0:00:01    |██▌                             | 36.1 MB 331 kB/s eta 0:21:14     |███                             | 43.8 MB 300 kB/s eta 0:23:02     |███                             | 44.5 MB 301 kB/s eta 0:22:54     |████                            | 56.5 MB 215 kB/s eta 0:31:07     |████▍                           | 63.6 MB 289 kB/s eta 0:22:44     |█████▎                          | 75.6 MB 93 kB/s eta 1:08:11     |█████▎                          | 76.3 MB 99 kB/s eta 1:04:14     |█████▊                          | 81.7 MB 124 kB/s eta 0:50:15     |██████▊                         | 96.4 MB 259 kB/s eta 0:23:15     |█████████▊                      | 139.8 MB 521 kB/s eta 0:10:12     |█████████▉                      | 140.7 MB 521 kB/s eta 0:10:09     |███████████▌                    | 164.9 MB 523 kB/s eta 0:09:21     |██████████████▎                 | 204.8 MB 1.0 MB/s eta 0:04:12     |████████████████                | 228.1 

  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.1
    Uninstalling numpy-1.20.1:
      Successfully uninstalled numpy-1.20.1
  Attempting uninstall: h5py
    Found existing installation: h5py 2.10.0
    Uninstalling h5py-2.10.0:
      Successfully uninstalled h5py-2.10.0
Note: you may need to restart the kernel to use updated packages.


In [12]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
indices = [1, 4, 2, 0, 3]
C = tf.constant(5, name = "C")
      
one_hot_matrix = tf.one_hot(
    indices, C, on_value = 1.0, off_value = 0.0, axis =-1)
  
sess = tf.compat.v1.Session()
  
one_hot = sess.run(one_hot_matrix)
  
sess.close()
  
# output is of dimension 5 x 5
print(one_hot)

[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [6]:
print(tf.__version__)

2.6.0


In [10]:
## bag of words

In [13]:
import nltk  
import numpy as np  
import random  
import string

import bs4 as bs  
import urllib.request  
import re  

In [14]:
raw_html = urllib.request.urlopen('https://en.wikipedia.org/wiki/Natural_language_processing')  
raw_html = raw_html.read()

article_html = bs.BeautifulSoup(raw_html, 'lxml')

article_paragraphs = article_html.find_all('p')

article_text = ''

for para in article_paragraphs:  
    article_text += para.text

In [15]:
corpus = nltk.sent_tokenize(article_text)

In [16]:
for i in range(len(corpus )):
    corpus [i] = corpus [i].lower()
    corpus [i] = re.sub(r'\W',' ',corpus [i])
    corpus [i] = re.sub(r'\s+',' ',corpus [i])

In [17]:
print(len(corpus))

49


In [18]:
print(corpus[30])

in some areas this shift has entailed substantial changes in how nlp systems are designed such that deep neural network based approaches may be viewed as a new paradigm distinct from statistical natural language processing 


In [19]:
wordfreq = {}
for sentence in corpus:
    tokens = nltk.word_tokenize(sentence)
    for token in tokens:
        if token not in wordfreq.keys():
            wordfreq[token] = 1
        else:
            wordfreq[token] += 1

In [21]:
len(wordfreq)

548

In [22]:
import heapq
most_freq = heapq.nlargest(200, wordfreq, key=wordfreq.get)

In [23]:
sentence_vectors = []
for sentence in corpus:
    sentence_tokens = nltk.word_tokenize(sentence)
    sent_vec = []
    for token in most_freq:
        if token in sentence_tokens:
            sent_vec.append(1)
        else:
            sent_vec.append(0)
    sentence_vectors.append(sent_vec)

In [26]:
sentence_vectors

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 0, ..., 1, 1, 0],
       [0, 1, 1, ..., 0, 0, 1],
       ...,
       [1, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [27]:
##             TF-IDF

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

In [30]:
Document1= "It is going to rain today."
Document2= "Today I am not going outside."
Document3= "I am going to watch the season premiere."
Doc = [Document1 ,
 Document2 , 
 Document3]
print(Doc)

['It is going to rain today.', 'Today I am not going outside.', 'I am going to watch the season premiere.']


In [33]:
X = vectorizer.fit_transform(Doc)
print(vectorizer.get_feature_names())

['am', 'going', 'is', 'it', 'not', 'outside', 'premiere', 'rain', 'season', 'the', 'to', 'today', 'watch']


In [41]:
analyze = vectorizer.build_analyzer()
print('Document 1',analyze(Document1))
print('Document 2',analyze(Document2))
print('Document 3',analyze(Document3))


Document 1 ['it', 'is', 'going', 'to', 'rain', 'today']
Document 2 ['today', 'am', 'not', 'going', 'outside']
Document 3 ['am', 'going', 'to', 'watch', 'the', 'season', 'premiere']


In [45]:
import pandas as pd
pd.DataFrame.sparse.from_spmatrix(X)

0         1        2        3         4         5         6   \
0  0.000000  0.278245  0.47111  0.47111  0.000000  0.000000  0.000000   
1  0.406192  0.315444  0.00000  0.00000  0.534093  0.534093  0.000000   
2  0.324124  0.251711  0.00000  0.00000  0.000000  0.000000  0.426184   

        7         8         9         10        11        12  
0  0.47111  0.000000  0.000000  0.358291  0.358291  0.000000  
1  0.00000  0.000000  0.000000  0.000000  0.406192  0.000000  
2  0.00000  0.426184  0.426184  0.324124  0.000000  0.426184

In [ ]:
## WORD2VEC

In [52]:

pip install gensim

Note: you may need to restart the kernel to use updated packages.


In [53]:
# importing all necessary modules
from nltk.tokenize import sent_tokenize, word_tokenize
import warnings
  
warnings.filterwarnings(action = 'ignore')
  
import gensim
from gensim.models import Word2Vec
  
#  Reads ‘alice.txt’ file
sample = open("alice.txt", "r")
s = sample.read()
  
# Replaces escape character with space
f = s.replace("\n", " ")
  
data = []
  
# iterate through each sentence in the file
for i in sent_tokenize(f):
    temp = []
      
    # tokenize the sentence into words
    for j in word_tokenize(i):
        temp.append(j.lower())
  
    data.append(temp)
  
# Create CBOW model
model1 = gensim.models.Word2Vec(data, min_count = 1, 
                              size = 100, window = 5)
  
# Print results
print("Cosine similarity between 'alice' " + 
               "and 'wonderland' - CBOW : ",
    model1.similarity('alice', 'wonderland'))
      
print("Cosine similarity between 'alice' " +
                 "and 'machines' - CBOW : ",
      model1.similarity('alice', 'machines'))
  
# Create Skip Gram model
model2 = gensim.models.Word2Vec(data, min_count = 1, size = 100,
                                             window = 5, sg = 1)
  
# Print results
print("Cosine similarity between 'alice' " +
          "and 'wonderland' - Skip Gram : ",
    model2.similarity('alice', 'wonderland'))
      
print("Cosine similarity between 'alice' " +
            "and 'machines' - Skip Gram : ",
      model2.similarity('alice', 'machines'))

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject